version: "1"
projects:
- name: Halalчсмчсмч
  environments:
  - name: Production
    services:
    # ВЕБ-СЕРВЕР (Flask + API)
    - type: web
      name: halal-shop-web
      runtime: python
      repo: https://github.com/FaranGe1t/halal-shop
      plan: free
      envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_RECEIPTS_PASSWORD
        sync: false
      - key: RENDER
        value: "true"
      - key: PUBLIC_URL
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn backend.main:app
      autoDeployTrigger: commit
      disk:
        name: halal-data
        mountPath: /opt/render/project/src/backend
        sizeGB: 1

    # WORKER ДЛЯ БОТА (кнопки, геолокация)
    - type: worker
      name: halal-shop-bot
      runtime: python
      repo: https://github.com/FaranGe1t/halal-shop
      plan: free
      envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_RECEIPTS_PASSWORD
        sync: false
      - key: RENDER
        value: "true"
      - key: PUBLIC_URL
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: python backend/bot_worker.py
      autoDeployTrigger: commit
